title: Jekyll, Ubuntu, and GitHub Pages
description: (V037-20200911)
      Just, GitHub Pages, Ubuntu, and Jekyll<br>
      This site is managed by VauLSMorg (vlsm.org) since 2020.
google_analytics: UA-89852122-6
author: "Mr. Yoda-Yoda"
theme: jekyll-theme-hacker
github: [metadata]

